# 服务端口号
server:
  port: 8080

########## 数据库配置 ##########
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coolw?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    # 连接池
    hikari:
      maximum-pool-size: 10
      max-lifetime: 1770000

########## mybatis ##########
mybatis:
  # mapper文件映射位置
  mapper-locations: classpath:/mapper/*.xml
  # 指定实体类别名
  type-aliases-package: com.coolw.mybatis.entity
  configuration:
    # 下划线自动转驼峰
    map-underscore-to-camel-case: true

# sql日志级别
logging:
  level:
    com.coolw.mybatis.dao: debug
