server:
  port: 8080

spring:
  # redis配置
  redis:
    host: 192.168.188.66
    port: 6379
    password: 123456
    database: 0
    timeout: 5000
    # jedis配置
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池中的最小空闲连接
        min-idle: 50
        # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
        max-active: 1000
        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        max-wait: 2000
      