server:
  port: 8080
  
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coolw?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    # hikari连接池
    hikari:
      # 最大连接池数
      maximum-pool-size: 10
      max-lifetime: 1770000
      
# mybatis
mybatis:
  type-aliases-package: com.coolw.transaction.entity
  mapper-locations: classpath:/mapper/*.xml

# 日志打印
logging:
  config:
    com.coolw.transaction.dao: debug